encyclopedia/urls.py
from django.urls import path

from . import views

app_name = 'encyclopedia'

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("wiki/<str:entry_title>/", views.view_entry, name="view_entry"),
    path("search/", views.search_entry, name="search_entry"),
    path("edit/<str:entry_title>/", views.edit, name="edit_entry"),
    path("random/", views.random_view_entry, name='random_view_entry')
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
import random

from django.shortcuts import render, redirect

from django import forms

from django.core.exceptions import ValidationError

from . import util

from markdown2 import Markdown

markdowner = Markdown()

class NewEntryForm(forms.Form):
    
    title = forms.CharField(label='title', max_length=50)
    body = forms.CharField(widget=forms.Textarea(attrs={"rows":8, "cols":10}))
    
    def clean_title(self):
        
        data = self.cleaned_data["title"]
        
        # When the page is saved, if an encyclopedia entry already exists with the provided title, the user should be presented with an error message.
        entry_list = util.list_entries()
        
        if data in entry_list:
            
            raise ValidationError('Error: This title is already used for another entry')
        
        return data

class EditEntryForm(forms.Form):
    
    # title = forms.CharField(label='title', max_length=50, disabled=True)
    body = forms.CharField(widget=forms.Textarea(attrs={"rows":8, "cols":10}))

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def create(request):
    
    if request.method == "POST":
        
        form = NewEntryForm(request.POST)
        
        if form.is_valid():
            
            form_data = {
                
                'title': form.cleaned_data['title'],
                'body' : form.cleaned_data['body']
                
            }
            
            # print('form_data: ')
            # print(form_data)
            
            # The encyclopedia entry should be saved to disk, and the user should be taken to the new entry’s page.
            util.save_entry(form_data["title"], form_data["body"])
            return redirect("encyclopedia:view_entry", entry_title=form_data["title"])
        
        else:
            
            return render(request, "encyclopedia/create_entry.html", {
                'form': form
            })
        
    else:
        
        form = NewEntryForm()
    
    
    return render(request, "encyclopedia/create_entry.html", {
        'form': form
    })

def edit(request, entry_title):
    
    # Edit Page: On each entry page, the user should be able to click a link to be taken to a page where the user can edit that entry’s Markdown content in a textarea. 
    
    print("accessing edit entry page")
    print("entry_title: ")
    print(entry_title)
    
    entry_data = util.get_entry(entry_title)
    
    
    if request.method == "POST":
        
        print("accessing edit entry page (POST Method)")
        
        form = EditEntryForm(request.POST)
        
        if form.is_valid():
            
            # print("ok: form value valid")
            
            form_data = {
                
                # 'title': form.cleaned_data['title'],
                'body' : form.cleaned_data['body']
                
            }
            
            # print('form_data: ')
            # print(form_data)
            
            # Once the entry is saved, the user should be redirected back to that entry’s page.
            util.save_entry(entry_title, form_data["body"])
            return redirect("encyclopedia:view_entry", entry_title=entry_title)
            
        else:
            
            print("error: form value not valid")
            print(form.errors.as_data())
            
            # The textarea should be pre-populated with the existing Markdown content of the page. (i.e., the existing content should be the initial value of the textarea).
            
            form = EditEntryForm(initial={"body": entry_data})
            
            return render(request, "encyclopedia/edit_entry.html", {
                'form': form,
                'entry_title': entry_title
            })
            
    else: 
        
        form = EditEntryForm(initial={"title": entry_title, "body": entry_data})
    
    
    return render(request, "encyclopedia/edit_entry.html", {
        'form': form,
        'entry_title': entry_title
    })

def view_entry(request, entry_title):

    print("entry_title: ")
    print(entry_title)

    entry_data = util.get_entry(entry_title)
    # print(entry_data)

    if entry_data == None:

            return render(request, "encyclopedia/no_entry_found.html", {
            "entries": util.list_entries(),
        })
    
    else:

        return render(request, "encyclopedia/view_entry.html", {
            "entry_title": entry_title,
            "entry_data": markdowner.convert(entry_data),
        })

def random_view_entry(request):

    # Clicking “Random Page” in the sidebar should take user to a random encyclopedia entry.

    entry_list = util.list_entries()

    random_entry = random.choice(entry_list)

    return redirect("encyclopedia:view_entry", entry_title=random_entry)

# Allow the user to type a query into the search box in the sidebar to search for an encyclopedia entry.
def search_entry(request):
    
    if request.method == "POST":
        
        entry_list = util.list_entries()
        search_result_list = []
        search_request = request.POST['query']
        
        # If the query matches the name of an encyclopedia entry, the user should be redirected to that entry’s page.
        if search_request in entry_list:
            
            return redirect("encyclopedia:view_entry", entry_title=search_request)
        
        # If the query does not match the name of an encyclopedia entry, the user should instead be taken to a search results page that displays a list of all encyclopedia entries that have the query as a substring.
        # For example, if the search query were ytho, then Python should appear in the search results.
        
        for entry in entry_list:
            
            if search_request in entry:
                
                search_result_list.append(entry)
        
        if len(search_result_list) != 0:
            
            return render(request, "encyclopedia/search_results.html", {
                "entries": search_result_list
            })
            
        else:
            
                return render(request, "encyclopedia/no_entry_found.html", {
                "entries": util.list_entries()
            })
            
    
    else: 
        
        # As this view isn't supposed to be directly accessed, without a post request, we redirect to home if the user try to access to search page, outside of the search form
        return redirect("encyclopedia:index")

encyclopedia/templates/encyclopedia/create_entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create new page
{% endblock %}

{% block body %}
    <h1>Create new page</h1>

    <form action="{% url 'encyclopedia:create' %}" method="post">

        {% csrf_token %}
        {{ form }}

        <input type="submit" value="Save">

    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/edit_entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit page
{% endblock %}

{% block body %}
    <h1>Edit page</h1>

    <h2> {{entry_title}} </h2>

    <form action="{% url 'encyclopedia:edit_entry' entry_title %}" method="post">

        {% csrf_token %}
        {{ form }}

        <input type="submit" value="Save" >

    </form>

    <div>

        <a href="{% url 'encyclopedia:view_entry' entry_title %}">Cancel</a>

    </div>    

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}

    <div class="container-fluid">

        <h1>All Pages</h1>

        <ul class="list-group">

            {% for entry in entries %}
                <li class="list-group-item"><a href="{% url 'encyclopedia:view_entry' entry %}">{{ entry }}</a></li>
            {% endfor %}

        </ul>

    </div>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action={% url 'encyclopedia:search_entry' %} method="post">

                    {% csrf_token %}

                    <input class="search" type="text" name="query" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random_view_entry' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/no_entry_found.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Entry Not Found
{% endblock %}

{% block body %}
    <h1>Entry Not Found</h1>

    <div>
        <p><strong>This entry does not exist !</strong></p>
    </div>

    <div>

        <p>See all the existing entries below</p>

    </div>
    <ul>
        {% for entry in entries %}
            <a href="{% url 'encyclopedia:view_entry' entry %}">{{ entry }}</a>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/search_results.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}

    <div class="container-fluid">

        <h1>Search Results</h1>

        <ul class="list-group">

            {% for entry in entries %}
                <li class="list-group-item"><a href="{% url 'encyclopedia:view_entry' entry %}">{{ entry }}</a></li>
            {% endfor %}

        </ul>

    </div>

{% endblock %}

encyclopedia/templates/encyclopedia/view_entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ entry_title }}
{% endblock %}

{% block body %}

    <div>
        {{entry_data |safe}}
    </div>

    <div>

        <a href="{% url 'encyclopedia:edit_entry' entry_title %}">Edit</a>

    </div>    

{% endblock %}